### ISSUE TITLE
集成错误

### ISSUE THREAD

**Issue by zeminli** [juhewu/juhewu-openfeign-spring-cloud-starter#1]
步骤1 - 创建一个springboot （spring-boot-starter-parent 2.7.3） 空工程
步骤2 - 添加 juhewu 1.0.3 依赖
步骤3 - 添加默认配置
步骤4 - 启动依赖报错

Caused by: java.lang.NoClassDefFoundError: org/springframework/cloud/openfeign/ribbon/CachingSpringLoadBalancerFactory
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[na:1.8.0_131]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[na:1.8.0_131]
	at java.lang.Class.getDeclaredMethods(Class.java:1975) ~[na:1.8.0_131]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:467) ~[spring-core-5.3.22.jar:5.3.22]
	... 36 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.cloud.openfeign.ribbon.CachingSpringLoadBalancerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_131]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335) ~[na:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_131]
	... 40 common frames omitted

**Comment by duan847** [comment]
该项目是扩展了spring-cloud-starter-openfeign，需要在微服务环境下使用，所以还需要以下依赖。项目结构已经重构，添加了示例模块，请参考。
```
<!--spring-boot-starter-web-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <!--nacos-discovery-->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>
        <!--openfeign-->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
        </dependency>
```

**Comment by zeminli** [comment]
我的场景是这样的，客户端和服务端不在一个eureka/nacos上~  客户端是独立运行在自己的环境中，只能通过 远程调用 服务端的接口，目的是 删除 httpclient or resttemplate方式调用，使用 feign的方式去调用 service.method() 方式~ 
问题：
原有客户端可能已经集成了 openfeign 或 版本兼容问题
